import algebra.algebra.basic
import algebra.big_operators
import algebra.big_operators.basic
import algebra.floor
import algebra.geom_sum
import algebra.group_power.basic
import algebra.ordered_group
import algebra.quadratic_discriminant
import algebra.ring.basic
import analysis.asymptotics.asymptotic_equivalent
import analysis.mean_inequalities
import analysis.normed_space.basic
import analysis.normed_space.pi_Lp
import analysis.special_functions.exp_log
import analysis.special_functions.pow
import analysis.special_functions.trigonometric
import combinatorics.simple_graph.basic
import data.complex.basic
import data.complex.exponential
import data.complex.is_R_or_C
import data.equiv.basic
import data.finset.basic
import data.finset.lattice
import data.finset.sort
import data.fintype.basic
import data.int.basic
import data.int.gcd
import data.int.modeq
import data.list.basic
import data.list.defs
import data.list.palindrome
import data.matrix.basic
import data.multiset.basic
import data.nat.basic
import data.nat.choose
import data.nat.choose.basic
import data.nat.digits
import data.nat.dist
import data.nat.fib
import data.nat.gcd
import data.nat.log
import data.nat.modeq
import data.nat.parity
import data.nat.prime
import data.pnat.basic
import data.pnat.prime
import data.polynomial
import data.polynomial.basic
import data.polynomial.degree.definitions
import data.polynomial.div
import data.polynomial.eval
import data.polynomial.ring_division
import data.rat.basic
import data.real.basic
import data.real.ennreal
import data.real.golden_ratio
import data.real.irrational
import data.real.nnreal
import data.real.pi
import data.real.sqrt
import data.set.basic
import data.set.intervals.basic
import data.zmod.basic
import geometry.euclidean.basic
import geometry.euclidean.circumcenter
import geometry.euclidean.monge_point
import geometry.euclidean.sphere
import init.data.nat.gcd
import linear_algebra.affine_space.affine_map
import linear_algebra.affine_space.independent
import linear_algebra.affine_space.ordered
import linear_algebra.finite_dimensional
import logic.basic
import measure_theory.interval_integral
import number_theory.arithmetic_function
import number_theory.divisors
import order.bounds
import order.filter.basic
import order.well_founded_set
import ring_theory.coprime
import ring_theory.polynomial.symmetric
import set_theory.fincard
import set_theory.lists
import system.random.basic
import topology.algebra.infinite_sum
import topology.basic
import topology.instances.nnreal
import topology.metric_space.basic
import imo_th

structure point (α : Type*) :=
(x : α) (y : α) (z : α)
